-- sums 2 numbers 2 + 2 -> 4
-- sum2 4 5 -> 9
-- 
-- computes n-th fibonacci number -- 0, 1, 1, 2, 3, 5, 8
-- fib 10 34
-- 
-- computes n-th factorial number
-- fact 5 -> 120
-- 
-- receives a list and returns the length of the list
-- length1 [1, 3, 4, 5] -> 4
-- 
-- returns the max element in the list
-- maxElement [1, 5, 3, 2, 4] -> 5
-- 
-- reverses a list
-- myReverse [1, 2, 3, 4, 5] -> [5, 4, 3, 2, 1]
-- 
-- member -> return true if the list contains the element false otherwise
-- member [1, 2, 3, 5, 3] 3 -> True
