-- append 2 lists toghether
-- append [1, 2, 3] [5, 6, 7] -> [1, 2, 3, 5, 6, 7]
-- 
-- remove the brackets from the inner lists
-- myFlatten [[1, 2, 3], [4, 5, 6]] -> [1, 2, 3, 4, 5, 6]
-- 
-- returns a list of the first n elements
-- myTake 3 [1, 2, 3, 4, 5] -> [1, 2, 3]
-- 
-- returns a list from the elements between the 2 given indexes
-- mySlice [1, 2, 3, 4, 5, 6, 7] 2 4 -> [3, 4, 5]
-- 
-- counts how many times the elements is found in the list
-- countOccurances [1, 2, 4, 5, 6, 5, 6] 5 -> 2
-- 
-- removes all occurances of the given element from the list
-- remove [1, 3, 5, 6, 3, 5, 3] 3 -> [1, 5, 6, 5] 
-- 
-- checks if the digits in the number are in descending order
-- isDescending 55544332222 -> True
-- 
-- find the divisors of the given number
-- divisors 15 -> [1, 3, 5, 15]
-- 
-- check if the given number is prime using one of the previous tasks
-- prime 7 -> True
-- prime 11 -> False
-- 
-- check if the first number ends with the second one
-- endsWith 145 45 -> True
-- endsWith 1456 5 -> false
